name: Plots CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Build]')"

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: NetherGamesMC/PharBuilder
          token: ${{ secrets.ng_token }}
          path: PharBuilder
          ref: PMMP4.0
      - name: Build
        run: |
          echo Building...
          chmod +x PharBuilder/BuildScript.php
          php -dphar.readonly=0 PharBuilder/BuildScript.php --make "" --out PharBuilder/NGPlots.phar
          echo Injecting Virions...
          php -dphar.readonly=0 PharBuilder/libasynql.phar PharBuilder/NGPlots.phar
          echo Build completed!
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: NGPlots
          path: PharBuilder/NGPlots.phar