name: PHPStan CI

on: push

jobs:
  phpstan:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Checkout NGEssentials
        uses: actions/checkout@v2
        with:
          repository: NetherGamesMC/NGEssentials
          token: ${{ secrets.ng_token }}
          submodules: true
          path: NGEssentials
          ref: PMMP4.0
      - name: Checkout PharBuilder
        uses: actions/checkout@v2
        with:
          repository: NetherGamesMC/PharBuilder
          token: ${{ secrets.ng_token }}
          path: PharBuilder
          ref: PMMP4.0
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist
